apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader-deployment
  namespace: homebroker
spec:
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
      - name: trader
        image: lucaslive974/trader-worker:v1
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service:9092"
          - name: KAFKA_GROUP_ID
            value: "myGroup"
          - name: KAFKA_AUTO_OFFSET_RESET
            value: "earliest"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"